"""
Utility functions for CCMTO experiments:
- Formatted JSON persistence adhering to Prettier styling
- Automatic cleanup of CEC2013 benchmark C++ artifact CSV files (results_f*.csv)
"""

import atexit
import glob
import json
import os
import shutil
import subprocess
from typing import Any, Optional


def cleanup_benchmark_csv(directory: Optional[str] = None) -> None:
    """
    Remove any results_f*.csv files generated by cec2013lsgo in the given directory,
    the current working directory, and the repository root.
    """
    dirs_to_clean = set()
    if directory:
        dirs_to_clean.add(os.path.abspath(directory))
    dirs_to_clean.add(os.path.abspath(os.getcwd()))
    
    # Project root directory (two levels up from src/utils.py)
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    dirs_to_clean.add(root_dir)

    for d in dirs_to_clean:
        if os.path.exists(d):
            for csv_file in glob.glob(os.path.join(d, "results_f*.csv")):
                try:
                    os.remove(csv_file)
                except OSError:
                    pass


def register_csv_cleanup() -> None:
    """
    Register an atexit hook to ensure results_f*.csv files are always removed
    when the Python process terminates.
    """
    atexit.register(cleanup_benchmark_csv)


def save_json(data: Any, out_path: str, format_prettier: bool = True) -> None:
    """
    Save JSON data to out_path with standard 2-space indentation,
    and optionally format with Prettier for clean compact formatting.
    """
    abs_out_path = os.path.abspath(out_path)
    os.makedirs(os.path.dirname(abs_out_path), exist_ok=True)

    with open(abs_out_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")

    if format_prettier:
        try:
            if shutil.which("prettier"):
                subprocess.run(
                    ["prettier", "--write", abs_out_path],
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            elif shutil.which("npx"):
                subprocess.run(
                    ["npx", "prettier", "--write", abs_out_path],
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
        except Exception:
            pass


# Auto-register cleanup on import
register_csv_cleanup()
